loot_table = {
    'ardo dirtpaw': [
        {'item': 'wolf pelt', 'rarity': 'common', 'drop_rate': 15},
        {'item': 'sharp fang', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'gold coin', 'rarity': 'common', 'drop_rate': 15},
        {'item': 'mossy stone', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'animal bone', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'dark shard', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'raw hide', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'rusted knife', 'rarity': 'uncommon', 'drop_rate': 5},
        {'item': 'bear claw', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'spiked collar', 'rarity': 'epic', 'drop_rate': 5}
    ],
    'blackrock battleworg': [
        {'item': 'battle claws', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'wolf hide', 'rarity': 'common', 'drop_rate': 15},
        {'item': 'iron dagger', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'branded pelt', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'battle shield', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'jagged fang', 'rarity': 'uncommon', 'drop_rate': 5},
        {'item': 'wolf meat', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'cracked stone', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'silver tooth', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'battle axe', 'rarity': 'epic', 'drop_rate': 5}
    ],
    'blackrock champion': [
        {'item': 'blackrock shield', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'steel sword', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'gold coin', 'rarity': 'common', 'drop_rate': 20},
        {'item': 'bronze helmet', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'battle armor', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'steel dagger', 'rarity': 'uncommon', 'drop_rate': 5},
        {'item': 'spiked gloves', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'warrior’s crest', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'tattered banner', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'serpent’s fang', 'rarity': 'uncommon', 'drop_rate': 10}
    ],
    'blackrock drake': [
        {'item': 'drake scale', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'fiery essence', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'dragon claw', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'scorched pelt', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'flame shard', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'lava crystal', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'drake leather', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'dragon heart', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'blazing ring', 'rarity': 'uncommon', 'drop_rate': 5},
        {'item': 'burnt scales', 'rarity': 'epic', 'drop_rate': 5}
    ],
    'blackrock drakerider': [
        {'item': 'rider spear', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'dragonhide boots', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'health potion', 'rarity': 'common', 'drop_rate': 20},
        {'item': 'rider’s cloak', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'fiery sword', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'soulstone', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'dragonbone staff', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'battle insignia', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'clawed gloves', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'dragon’s blood', 'rarity': 'epic', 'drop_rate': 5}
    ],
    'blackrock gladiator': [
        {'item': 'gladiator helmet', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'iron gauntlets', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'arena badge', 'rarity': 'common', 'drop_rate': 20},
        {'item': 'gladiator’s sword', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'battle boots', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'spiked chestplate', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'iron shield', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'gilded armor', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'bloodstained banner', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'warrior’s insignia', 'rarity': 'uncommon', 'drop_rate': 10}
    ],
    'blackrock guard': [
        {'item': 'guard spear', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'chainmail armor', 'rarity': 'common', 'drop_rate': 15},
        {'item': 'gold coin', 'rarity': 'common', 'drop_rate': 20},
        {'item': 'wooden shield', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'iron boots', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'iron mace', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'guard insignia', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'garrison token', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'cracked helm', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'guard’s ring', 'rarity': 'epic', 'drop_rate': 5}
    ],
    'blackrock hunter': [
        {'item': 'hunting bow', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'quiver of arrows', 'rarity': 'common', 'drop_rate': 20},
        {'item': 'wolf hide', 'rarity': 'common', 'drop_rate': 20},
        {'item': 'sharp arrow', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'sturdy boots', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'tracking compass', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'hunting knife', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'iron arrows', 'rarity': 'common', 'drop_rate': 5},
        {'item': 'beast talon', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'hunter’s cloak', 'rarity': 'epic', 'drop_rate': 5}
    ],
    'blackrock overseer': [
        {'item': 'overseer mace', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'command insignia', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'iron key', 'rarity': 'common', 'drop_rate': 20},
        {'item': 'red scroll', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'golden ring', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'overseer’s helmet', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'iron chainmail', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'crimson shard', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'golden coin pouch', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'oversized shield', 'rarity': 'uncommon', 'drop_rate': 10}
    ],
    'blackrock renegade': [
        {'item': 'renegade blade', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'dark cloak', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'smoke bomb', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'broken sword', 'rarity': 'common', 'drop_rate': 15},
        {'item': 'renegade boots', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'shadow gem', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'stolen map', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'renegade gloves', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'dark robe', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'mysterious potion', 'rarity': 'uncommon', 'drop_rate': 10}
    ],
    'blackrock shadowcaster': [
        {'item': 'shadow staff', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'mana crystal', 'rarity': 'common', 'drop_rate': 15},
        {'item': 'enchanted cloak', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'dark orb', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'arcane tome', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'shadow crystal', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'mana potion', 'rarity': 'common', 'drop_rate': 20},
        {'item': 'purple shard', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'shadow dust', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'caster’s ring', 'rarity': 'epic', 'drop_rate': 5}
    ],
    'blackrock warden': [
        {'item': 'warden key', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'iron shield', 'rarity': 'common', 'drop_rate': 15},
        {'item': 'warden badge', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'broken lock', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'worn sword', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'warden’s helm', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'rusted chainmail', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'iron boots', 'rarity': 'uncommon', 'drop_rate': 5},
        {'item': 'glowing crystal', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'ancient tome', 'rarity': 'uncommon', 'drop_rate': 5}
    ],
    'blackrock worg captain': [
        {'item': 'worg fang', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'leather armor', 'rarity': 'common', 'drop_rate': 15},
        {'item': 'silver coin', 'rarity': 'common', 'drop_rate': 20},
        {'item': 'captain’s sword', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'tattered cloak', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'worg hide', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'wolf talon', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'captain’s ring', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'leather gloves', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'worg tooth', 'rarity': 'uncommon', 'drop_rate': 10}
    ],
    'canyon ettin': [
        {'item': 'ettin club', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'giant bone', 'rarity': 'common', 'drop_rate': 15},
        {'item': 'mystic gem', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'ettin hide', 'rarity': 'common', 'drop_rate': 15},
        {'item': 'giant’s ear', 'rarity': 'uncommon', 'drop_rate': 5},
        {'item': 'mighty axe', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'ancient charm', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'iron ring', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'giant’s skull', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'ettin pouch', 'rarity': 'rare', 'drop_rate': 5}
    ],
'cow': [
    {'item': 'N/A', 'rarity': 'N/A', 'N/A': 0}
],
'dire condor': [
        {'item': 'condor feather', 'rarity': 'common', 'drop_rate': 20},
        {'item': 'sharp talon', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'gold coin', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'winged leather', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'feathered cap', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'claw necklace', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'vulture’s beak', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'bird’s talon', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'sharp arrow', 'rarity': 'common', 'drop_rate': 5},
        {'item': 'condor’s wings', 'rarity': 'epic', 'drop_rate': 5}
    ],
    'gathllzog': [
        {'item': 'orc axe', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'battle totem', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'gold pouch', 'rarity': 'common', 'drop_rate': 20},
        {'item': 'gathllzog’s armor', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'orc necklace', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'giant’s tooth', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'battle trophy', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'orc’s belt', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'orcish banner', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'orcish shield', 'rarity': 'uncommon', 'drop_rate': 10}
    ],
    'general fangcore': [
        {'item': 'fangcore sword', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'general’s insignia', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'treasure map', 'rarity': 'common', 'drop_rate': 15},
        {'item': 'fangcore armor', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'general’s gloves', 'rarity': 'uncommon', 'drop_rate': 5},
        {'item': 'battle flag', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'general’s ring', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'warrior’s cloak', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'fangcore helmet', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'general’s boots', 'rarity': 'uncommon', 'drop_rate': 10}
    ],
    'gnollfeaster': [
        {'item': 'gnoll tooth', 'rarity': 'common', 'drop_rate': 25},
        {'item': 'feast scraps', 'rarity': 'common', 'drop_rate': 20},
        {'item': 'bone charm', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'gnoll’s cloak', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'feaster’s talon', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'gnoll axe', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'gnoll chainmail', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'golden ring', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'gnoll’s key', 'rarity': 'uncommon', 'drop_rate': 5},
        {'item': 'gnoll’s bone necklace', 'rarity': 'epic', 'drop_rate': 5}
    ],
    'great goretusk': [
        {'item': 'goretusk hide', 'rarity': 'common', 'drop_rate': 20},
        {'item': 'boar tusk', 'rarity': 'common', 'drop_rate': 20},
        {'item': 'meat chunk', 'rarity': 'common', 'drop_rate': 20},
        {'item': 'goretusk tusk', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'boar’s leather', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'sharp tusk', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'wild boar meat', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'goretusk bone', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'goretusk head', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'boar’s shield', 'rarity': 'uncommon', 'drop_rate': 5}
    ],
    'impaled blackrock orc': [
        {'item': 'orc axe', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'iron ring', 'rarity': 'common', 'drop_rate': 15},
        {'item': 'shattered spear', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'orcish boots', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'impaled trophy', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'orcish shield', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'orc’s belt', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'bone dagger', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'orcish cloak', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'orcish warhammer', 'rarity': 'rare', 'drop_rate': 5}
    ],
    'kazon': [
        {'item': 'kazon’s staff', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'dark amulet', 'rarity': 'rare', 'drop_rate': 15},
        {'item': 'spellbook', 'rarity': 'uncommon', 'drop_rate': 20},
        {'item': 'kazon’s robe', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'arcane dust', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'kazon’s ring', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'kazon’s hood', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'staff of power', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'mana gem', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'kazon’s boots', 'rarity': 'uncommon', 'drop_rate': 5}
    ],
    'mountain cottontail': [
        {'item': 'N/A', 'rarity': 'N/A', 'N/A': 0}
    ],
    'murloc any': [
        {'item': 'murloc scale', 'rarity': 'common', 'drop_rate': 30},
        {'item': 'slimy pearl', 'rarity': 'uncommon', 'drop_rate': 25},
        {'item': 'gold coin', 'rarity': 'common', 'drop_rate': 20},
        {'item': 'murloc teeth', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'slime mucus', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'murloc eye', 'rarity': 'uncommon', 'drop_rate': 5},
        {'item': 'murloc spear', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'murloc skin', 'rarity': 'uncommon', 'drop_rate': 5},
        {'item': 'murloc’s crown', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'murloc staff', 'rarity': 'epic', 'drop_rate': 5}
    ],
    'overlord barbarius': [
        {'item': 'barbarius axe', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'warrior’s belt', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'rare gem', 'rarity': 'uncommon', 'drop_rate': 20},
        {'item': 'barbarius shield', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'overlord’s helmet', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'battle banner', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'overlord’s cloak', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'warrior’s ring', 'rarity': 'common', 'drop_rate': 15},
        {'item': 'warrior’s boots', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'barbarius dagger', 'rarity': 'rare', 'drop_rate': 5}
    ],
    'redridge any': [
        {'item': 'villager’s cloak', 'rarity': 'common', 'drop_rate': 20},
        {'item': 'simple boots', 'rarity': 'common', 'drop_rate': 15},
        {'item': 'silver coin', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'rusty sword', 'rarity': 'uncommon', 'drop_rate': 5},
        {'item': 'silver ring', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'village key', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'rusty shield', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'village necklace', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'leather pouch', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'village cloak', 'rarity': 'rare', 'drop_rate': 5}
    ],
    'redridge citizen female': [
        {'item': 'N/A', 'rarity': 'N/A', 'N/A': 0}
    ],
    'redridge citizen male': [
        {'item': 'N/A', 'rarity': 'N/A', 'N/A': 0}
    ],
'redridge fox': [
        {'item': 'fox fur', 'rarity': 'common', 'drop_rate': 50},
        {'item': 'sharp claw', 'rarity': 'uncommon', 'drop_rate': 30},
        {'item': 'small gem', 'rarity': 'common', 'drop_rate': 15},
        {'item': 'fox tail', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'fox paw necklace', 'rarity': 'uncommon', 'drop_rate': 5},
        {'item': 'sharp fang', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'fox’s pelt', 'rarity': 'common', 'drop_rate': 5},
        {'item': 'fox’s tooth', 'rarity': 'uncommon', 'drop_rate': 5},
        {'item': 'gold coin', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'fox fur boots', 'rarity': 'rare', 'drop_rate': 5}
    ],
    'redridge garrison watchman': [
        {'item': 'N/A', 'rarity': 'N/A', 'N/A': 0}
    ],
    'redridge mystic': [
        {'item': 'mystic staff', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'mana potion', 'rarity': 'common', 'drop_rate': 20},
        {'item': 'ancient scroll', 'rarity': 'uncommon', 'drop_rate': 30},
        {'item': 'mystic robe', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'mystic gem', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'mana crystal', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'mystic ring', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'arcane orb', 'rarity': 'uncommon', 'drop_rate': 5},
        {'item': 'mystic boots', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'mystic tome', 'rarity': 'epic', 'drop_rate': 5}
    ],
    'seeker aqualon': [
        {'item': 'aqualon’s staff', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'water orb', 'rarity': 'rare', 'drop_rate': 15},
        {'item': 'pearl necklace', 'rarity': 'uncommon', 'drop_rate': 20},
        {'item': 'aqualon’s cloak', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'water crystal', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'aqualon’s ring', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'aqualon’s boots', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'waterstone', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'aqualon’s staff shard', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'oceanic gem', 'rarity': 'uncommon', 'drop_rate': 10}
    ],
    'shadowhide darkweaver': [
        {'item': 'darkweaver robe', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'shadow crystal', 'rarity': 'uncommon', 'drop_rate': 20},
        {'item': 'gold coin', 'rarity': 'common', 'drop_rate': 40},
        {'item': 'shadowstaff', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'darkweaver boots', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'dark cloak', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'shadow gem', 'rarity': 'common', 'drop_rate': 5},
        {'item': 'shadowhide key', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'mana shard', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'shadowhide belt', 'rarity': 'common', 'drop_rate': 10}
    ],
    'shadowhide gnoll': [
        {'item': 'gnoll club', 'rarity': 'common', 'drop_rate': 30},
        {'item': 'worn armor', 'rarity': 'common', 'drop_rate': 20},
        {'item': 'silver coin', 'rarity': 'common', 'drop_rate': 25},
        {'item': 'gnoll ring', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'gnoll cloak', 'rarity': 'uncommon', 'drop_rate': 5},
        {'item': 'gnoll blade', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'gnoll dagger', 'rarity': 'common', 'drop_rate': 5},
        {'item': 'gnoll shield', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'gnoll fangs', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'gnoll’s key', 'rarity': 'rare', 'drop_rate': 5}
    ],
'shadowhide warrior': [
        {'item': 'warrior blade', 'rarity': 'uncommon', 'drop_rate': 40},
        {'item': 'iron shield', 'rarity': 'common', 'drop_rate': 25},
        {'item': 'gold coin', 'rarity': 'common', 'drop_rate': 30},
        {'item': 'warrior helm', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'shadowhide ring', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'warrior’s axe', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'warrior’s boots', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'warrior’s belt', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'iron sword', 'rarity': 'common', 'drop_rate': 5},
        {'item': 'shadowhide cape', 'rarity': 'uncommon', 'drop_rate': 5}
    ],
    'snareflare': [
        {'item': 'flare wand', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'fire crystal', 'rarity': 'uncommon', 'drop_rate': 30},
        {'item': 'burnt robe', 'rarity': 'common', 'drop_rate': 40},
        {'item': 'flame potion', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'flare powder', 'rarity': 'common', 'drop_rate': 5},
        {'item': 'flame dagger', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'fire cloak', 'rarity': 'uncommon', 'drop_rate': 5},
        {'item': 'snareflare’s horn', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'fire wand shard', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'snareflare’s token', 'rarity': 'uncommon', 'drop_rate': 10}
    ],
    'squiddic': [
        {'item': 'squid tentacle', 'rarity': 'common', 'drop_rate': 50},
        {'item': 'ink sac', 'rarity': 'uncommon', 'drop_rate': 30},
        {'item': 'pearl', 'rarity': 'rare', 'drop_rate': 15},
        {'item': 'squid eye', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'squid skin', 'rarity': 'common', 'drop_rate': 20},
        {'item': 'squid ink bottle', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'squid tusk', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'squid fin', 'rarity': 'common', 'drop_rate': 5},
        {'item': 'squid meat', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'deep-sea charm', 'rarity': 'rare', 'drop_rate': 5}
    ],
    'tarantula': [
        {'item': 'spider silk', 'rarity': 'common', 'drop_rate': 50},
        {'item': 'poison sac', 'rarity': 'uncommon', 'drop_rate': 30},
        {'item': 'sharp fang', 'rarity': 'common', 'drop_rate': 15},
        {'item': 'venom fang', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'spider eye', 'rarity': 'uncommon', 'drop_rate': 10},
        {'item': 'tarantula leg', 'rarity': 'common', 'drop_rate': 20},
        {'item': 'spider venom', 'rarity': 'uncommon', 'drop_rate': 5},
        {'item': 'spider webbing', 'rarity': 'common', 'drop_rate': 10},
        {'item': 'sharp claw', 'rarity': 'uncommon', 'drop_rate': 5},
        {'item': 'spider charm', 'rarity': 'rare', 'drop_rate': 5}
    ],
    'yowler(redridge boss)': [
        {'item': 'yowler’s claw', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'boss token', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'gold chest', 'rarity': 'legendary', 'drop_rate': 2},
        {'item': 'redridge boss’s cape', 'rarity': 'rare', 'drop_rate': 5},
        {'item': 'redridge boss’s crown', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'yowler’s fang', 'rarity': 'epic', 'drop_rate': 5},
        {'item': 'yowler’s tooth', 'rarity': 'uncommon', 'drop_rate': 15},
        {'item': 'yowler’s token', 'rarity': 'rare', 'drop_rate': 10},
        {'item': 'golden tooth', 'rarity': 'legendary', 'drop_rate': 2},
        {'item': 'yowler’s robe', 'rarity': 'uncommon', 'drop_rate': 5}
    ]
}
